<?xml version='1.0' encoding='UTF-8'?>

<bag xmlns:int="http://www.w3.org/2001/XMLSchema#int" xmlns:long="http://www.w3.org/2001/XMLSchema#long">
 <message_entry_t int:status="0" cap="Failed to finalize the result" msg="" long:timeStamp="1634764050897">
  <message msg="Using result path `/gpfs/mira-home/cadams/Theta/larcv3_scaling/larcv_io_testing/r000hs'" int:severity="1"/>
  <message msg="The database has been cleared, elapsed time is 0.502 seconds." int:severity="16"/>
  <message msg="The current result was collected on another host. For proper symbol resolution, please specify search directories for the binaries of interest using the -search-dir command line option or &quot;Binary/Symbol Search&quot; dialog in GUI." int:severity="2"/>
  <message msg="Cannot load data file `/gpfs/mira-home/cadams/Theta/larcv3_scaling/larcv_io_testing/r000hs/data.0/emon.0.emon' (Failed to read CPU topology information!)." int:severity="4"/>
  <message msg="Raw data has been loaded to the database, elapsed time is 5.140 seconds." int:severity="16"/>
  <message msg="Data transformations have been finished, elapsed time is 0.019 seconds." int:severity="16"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/pinruntime/libc-dynamic.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libiomp5.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/cray/pe/atp/3.6.4/lib/libAtpSigHandler.so.1'." int:severity="2"/>
  <message msg="Cannot locate file `/lus/theta-fs0/software/interpreters/python/3.6/intel/2019.3.075/bin/../lib/libpython3.6m.so.1.0'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libintlc.so.5'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_intel_lp64.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/pinruntime/libpin3dwarf.so'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/libc.so.6'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/libpthread.so.0'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/ld-linux-x86-64.so.2'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/bin64/pinbin'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so'." int:severity="2"/>
  <message msg="Cannot locate file `/lus/theta-fs0/software/interpreters/python/3.6/intel/2019.3.075/bin/python3.6'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/libm.so.6'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/runtime/libittnotify_collector.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/pinruntime/libstlport-dynamic.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/gcc/9.3.0/snos/lib64/libstdc++.so.6'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/libdl.so.2'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_avx512_mic.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/libtpsstool.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/lib-dynload/../../libcrypto.so.1.0.0'." int:severity="2"/>
  <message msg="Cannot locate file `/lus/grand/projects/datascience/cadams/theta-larcv-io/lib/libhdf5.so.200'." int:severity="2"/>
  <message msg="Cannot locate file `/lus/grand/projects/datascience/cadams/theta-larcv-io/lib/python3.6/site-packages/larcv-3.4.0-py3.6-linux-x86_64.egg/larcv/pylarcv.cpython-36m-x86_64-linux-gnu.so'." int:severity="2"/>
  <message msg="Cannot locate file `/lus/grand/projects/datascience/cadams/theta-larcv-io/lib/python3.6/site-packages/larcv-3.4.0-py3.6-linux-x86_64.egg/larcv/lib/liblarcv3.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/lib-dynload/../../libz.so.1'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_core.so'." int:severity="2"/>
  <message msg="Symbol resolution has been finished, elapsed time is 0.452 seconds." int:severity="16"/>
  <message msg="Deferred data transformations have been finished, elapsed time is 0.168 seconds." int:severity="16"/>
  <message msg="Data model parameters have been set, elapsed time is 0.031 seconds." int:severity="16"/>
  <message msg="Precomputing frequently used data has been finished, elapsed time is 0.098 seconds." int:severity="16"/>
  <message msg="Redundant overtime data has been discarded, elapsed time is 0.010 seconds." int:severity="16"/>
  <message msg="Raw collector data has been discarded, elapsed time is 0.000 seconds." int:severity="16"/>
  <message msg="Finalizing the result took 7.851 seconds." int:severity="16"/>
 </message_entry_t>
 <message_entry_t int:status="0" cap="Failed to finalize the result" msg="" long:timeStamp="1634764127923">
  <message msg="Using result path `/gpfs/mira-home/cadams/Theta/larcv3_scaling/larcv_io_testing/r000hs'" int:severity="1"/>
  <message msg="The database has been cleared, elapsed time is 0.561 seconds." int:severity="16"/>
  <message msg="The current result was collected on another host. For proper symbol resolution, please specify search directories for the binaries of interest using the -search-dir command line option or &quot;Binary/Symbol Search&quot; dialog in GUI." int:severity="2"/>
  <message msg="Cannot load data file `/gpfs/mira-home/cadams/Theta/larcv3_scaling/larcv_io_testing/r000hs/data.0/emon.0.emon' (Failed to read CPU topology information!)." int:severity="4"/>
  <message msg="Raw data has been loaded to the database, elapsed time is 4.728 seconds." int:severity="16"/>
  <message msg="Data transformations have been finished, elapsed time is 0.019 seconds." int:severity="16"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/pinruntime/libc-dynamic.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libiomp5.so'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/libc.so.6'." int:severity="2"/>
  <message msg="Cannot locate file `/lus/theta-fs0/software/interpreters/python/3.6/intel/2019.3.075/bin/python3.6'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libintlc.so.5'." int:severity="2"/>
  <message msg="Cannot locate file `/lus/theta-fs0/software/interpreters/python/3.6/intel/2019.3.075/bin/../lib/libpython3.6m.so.1.0'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/lib-dynload/../../libcrypto.so.1.0.0'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_intel_lp64.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/cray/pe/atp/3.6.4/lib/libAtpSigHandler.so.1'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/lib-dynload/../../libz.so.1'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/bin64/pinbin'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/libm.so.6'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/ld-linux-x86-64.so.2'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/pinruntime/libstlport-dynamic.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/gcc/9.3.0/snos/lib64/libstdc++.so.6'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_avx512_mic.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/pinruntime/libpin3dwarf.so'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/libdl.so.2'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/libtpsstool.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_core.so'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/libpthread.so.0'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/runtime/libittnotify_collector.so'." int:severity="2"/>
  <message msg="Symbol resolution has been finished, elapsed time is 0.991 seconds." int:severity="16"/>
  <message msg="Deferred data transformations have been finished, elapsed time is 0.163 seconds." int:severity="16"/>
  <message msg="Data model parameters have been set, elapsed time is 0.027 seconds." int:severity="16"/>
  <message msg="Precomputing frequently used data has been finished, elapsed time is 0.106 seconds." int:severity="16"/>
  <message msg="Redundant overtime data has been discarded, elapsed time is 0.005 seconds." int:severity="16"/>
  <message msg="Raw collector data has been discarded, elapsed time is 0.000 seconds." int:severity="16"/>
  <message msg="Finalizing the result took 7.923 seconds." int:severity="16"/>
 </message_entry_t>
 <message_entry_t int:status="2" cap="Failed to finalize the result" msg="0x40000003 (Unexpected internal error / invalid state) -- The result cannot be finalized in the file system that does not support file memory mapping. You can copy the result to a file system with file memory mapping support and use &quot;vtune -finalize -r &lt;result_directory&gt;&quot; to proceed with finalization, or re-run the analysis using the &quot;-r&quot; option to specify the result directory on a file system with file memory mapping support." long:timeStamp="1634828015469">
  <message msg="Using result path `/gpfs/mira-home/cadams/Theta/larcv3_scaling/larcv_io_testing/r001hs'" int:severity="1"/>
  <message msg="The database has been cleared, elapsed time is 0.887 seconds." int:severity="16"/>
  <message msg="Finalizing the result took 0.996 seconds." int:severity="16"/>
 </message_entry_t>
 <message_entry_t int:status="0" cap="Failed to finalize the result" msg="" long:timeStamp="1634828034981">
  <message msg="Using result path `/gpfs/mira-home/cadams/Theta/larcv3_scaling/larcv_io_testing/r001hs'" int:severity="1"/>
  <message msg="The database has been cleared, elapsed time is 0.605 seconds." int:severity="16"/>
  <message msg="The current result was collected on another host. For proper symbol resolution, please specify search directories for the binaries of interest using the -search-dir command line option or &quot;Binary/Symbol Search&quot; dialog in GUI." int:severity="2"/>
  <message msg="Cannot load data file `/gpfs/mira-home/cadams/Theta/larcv3_scaling/larcv_io_testing/r001hs/data.0/emon.0.emon' (Failed to read CPU topology information!)." int:severity="4"/>
  <message msg="Raw data has been loaded to the database, elapsed time is 3.164 seconds." int:severity="16"/>
  <message msg="Data transformations have been finished, elapsed time is 0.015 seconds." int:severity="16"/>
  <message msg="Cannot locate file `/lus/grand/projects/datascience/cadams/theta-larcv-io/lib/python3.6/site-packages/larcv-3.4.0-py3.6-linux-x86_64.egg/larcv/queueloader.py'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/pinruntime/libc-dynamic.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/pinruntime/libstlport-dynamic.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/pinruntime/libpin3dwarf.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_core.so'." int:severity="2"/>
  <message msg="Cannot locate file `/lus/grand/projects/datascience/cadams/theta-larcv-io/lib/python3.6/site-packages/larcv-3.4.0-py3.6-linux-x86_64.egg/larcv/lib/liblarcv3.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_intel_lp64.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/cray/pe/atp/3.6.4/lib/libAtpSigHandler.so.1'." int:severity="2"/>
  <message msg="Cannot locate file `/lus/theta-fs0/software/interpreters/python/3.6/intel/2019.3.075/bin/../lib/libpython3.6m.so.1.0'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/libc.so.6'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/ld-linux-x86-64.so.2'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/lib-dynload/_bisect.cpython-36m-x86_64-linux-gnu.so'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/libdl.so.2'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/libtpsstool.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/gcc/9.3.0/snos/lib64/libstdc++.so.6'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_avx512_mic.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/bin64/pinbin'." int:severity="2"/>
  <message msg="Cannot locate file `/usr/lib64/libnuma.so.1'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/lib-dynload/../../libcrypto.so.1.0.0'." int:severity="2"/>
  <message msg="Cannot locate file `/lus/theta-fs0/software/interpreters/python/3.6/intel/2019.3.075/bin/python3.6'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/lib-dynload/../../libz.so.1'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/libm.so.6'." int:severity="2"/>
  <message msg="Cannot locate file `/lus/grand/projects/datascience/cadams/theta-larcv-io/lib/libhdf5.so.200'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libintlc.so.5'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/libpthread.so.0'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/runtime/libittnotify_collector.so'." int:severity="2"/>
  <message msg="Symbol resolution has been finished, elapsed time is 0.516 seconds." int:severity="16"/>
  <message msg="Deferred data transformations have been finished, elapsed time is 0.187 seconds." int:severity="16"/>
  <message msg="Data model parameters have been set, elapsed time is 0.025 seconds." int:severity="16"/>
  <message msg="Precomputing frequently used data has been finished, elapsed time is 0.110 seconds." int:severity="16"/>
  <message msg="Redundant overtime data has been discarded, elapsed time is 0.007 seconds." int:severity="16"/>
  <message msg="Raw collector data has been discarded, elapsed time is 0.000 seconds." int:severity="16"/>
  <message msg="Finalizing the result took 5.821 seconds." int:severity="16"/>
 </message_entry_t>
 <message_entry_t int:status="0" cap="Failed to finalize the result" msg="" long:timeStamp="1634828062716">
  <message msg="Using result path `/gpfs/mira-home/cadams/Theta/larcv3_scaling/larcv_io_testing/r001hs'" int:severity="1"/>
  <message msg="The database has been cleared, elapsed time is 0.479 seconds." int:severity="16"/>
  <message msg="The current result was collected on another host. For proper symbol resolution, please specify search directories for the binaries of interest using the -search-dir command line option or &quot;Binary/Symbol Search&quot; dialog in GUI." int:severity="2"/>
  <message msg="Cannot load data file `/gpfs/mira-home/cadams/Theta/larcv3_scaling/larcv_io_testing/r001hs/data.0/emon.0.emon' (Failed to read CPU topology information!)." int:severity="4"/>
  <message msg="Raw data has been loaded to the database, elapsed time is 3.544 seconds." int:severity="16"/>
  <message msg="Data transformations have been finished, elapsed time is 0.018 seconds." int:severity="16"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/lib-dynload/../../libz.so.1'." int:severity="2"/>
  <message msg="Cannot locate file `/usr/lib64/libnuma.so.1'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/pinruntime/libc-dynamic.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/pinruntime/libstlport-dynamic.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/lib-dynload/../../libcrypto.so.1.0.0'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_avx512_mic.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_intel_lp64.so'." int:severity="2"/>
  <message msg="Cannot locate file `/lus/theta-fs0/software/interpreters/python/3.6/intel/2019.3.075/bin/../lib/libpython3.6m.so.1.0'." int:severity="2"/>
  <message msg="Cannot locate file `/lus/theta-fs0/software/interpreters/python/3.6/intel/2019.3.075/bin/python3.6'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/libc.so.6'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/ld-linux-x86-64.so.2'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/lib-dynload/_bisect.cpython-36m-x86_64-linux-gnu.so'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/libm.so.6'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/gcc/9.3.0/snos/lib64/libstdc++.so.6'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_core.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/cray/pe/atp/3.6.4/lib/libAtpSigHandler.so.1'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/pinruntime/libpin3dwarf.so'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/libpthread.so.0'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/runtime/libittnotify_collector.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libintlc.so.5'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/bin64/pinbin'." int:severity="2"/>
  <message msg="Cannot locate file `/lib64/libdl.so.2'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/libtpsstool.so'." int:severity="2"/>
  <message msg="Symbol resolution has been finished, elapsed time is 3.254 seconds." int:severity="16"/>
  <message msg="Deferred data transformations have been finished, elapsed time is 0.140 seconds." int:severity="16"/>
  <message msg="Data model parameters have been set, elapsed time is 0.029 seconds." int:severity="16"/>
  <message msg="Precomputing frequently used data has been finished, elapsed time is 0.106 seconds." int:severity="16"/>
  <message msg="Redundant overtime data has been discarded, elapsed time is 0.005 seconds." int:severity="16"/>
  <message msg="Raw collector data has been discarded, elapsed time is 0.000 seconds." int:severity="16"/>
  <message msg="Finalizing the result took 8.774 seconds." int:severity="16"/>
 </message_entry_t>
 <message_entry_t int:status="0" cap="Failed to finalize the result" msg="" long:timeStamp="1634828169777">
  <message msg="Using result path `/gpfs/mira-home/cadams/Theta/larcv3_scaling/larcv_io_testing/r001hs'" int:severity="1"/>
  <message msg="The database has been cleared, elapsed time is 0.484 seconds." int:severity="16"/>
  <message msg="The current result was collected on another host. For proper symbol resolution, please specify search directories for the binaries of interest using the -search-dir command line option or &quot;Binary/Symbol Search&quot; dialog in GUI." int:severity="2"/>
  <message msg="Cannot load data file `/gpfs/mira-home/cadams/Theta/larcv3_scaling/larcv_io_testing/r001hs/data.0/emon.0.emon' (Failed to read CPU topology information!)." int:severity="4"/>
  <message msg="Raw data has been loaded to the database, elapsed time is 4.101 seconds." int:severity="16"/>
  <message msg="Data transformations have been finished, elapsed time is 0.017 seconds." int:severity="16"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_rt.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libiomp5.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_intel_thread.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_intel_lp64.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/gcc/9.3.0/snos/lib64/libstdc++.so.6'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/runtime/libittnotify_collector.so'." int:severity="2"/>
  <message msg="Cannot locate file `/usr/lib64/libmemkind.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/cray/pe/atp/3.6.4/lib/libAtpSigHandler.so.1'." int:severity="2"/>
  <message msg="Cannot locate debugging information for file `/lib64/ld-linux-x86-64.so.2'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_avx512_mic.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/pinruntime/libpin3dwarf.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/pinruntime/libc-dynamic.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_core.so'." int:severity="2"/>
  <message msg="Cannot locate file `/lus/theta-fs0/software/interpreters/python/3.6/intel/2019.3.075/bin/../lib/libpython3.6m.so.1.0'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/pinruntime/libstlport-dynamic.so'." int:severity="2"/>
  <message msg="Cannot locate debugging information for file `/lib64/libdl.so.2'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/libtpsstool.so'." int:severity="2"/>
  <message msg="Cannot locate debugging information for file `/lib64/libc.so.6'." int:severity="2"/>
  <message msg="Cannot locate debugging information for file `/lib64/libpthread.so.0'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/lib-dynload/../../libcrypto.so.1.0.0'." int:severity="2"/>
  <message msg="Cannot locate debugging information for file `/lib64/libz.so.1'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/lib-dynload/_bisect.cpython-36m-x86_64-linux-gnu.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libintlc.so.5'." int:severity="2"/>
  <message msg="Cannot locate file `/lus/theta-fs0/software/interpreters/python/3.6/intel/2019.3.075/bin/python3.6'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/bin64/pinbin'." int:severity="2"/>
  <message msg="Cannot locate debugging information for file `/lib64/libm.so.6'." int:severity="2"/>
  <message msg="Cannot locate file `/usr/lib64/libnuma.so.1'." int:severity="2"/>
  <message msg="Symbol resolution has been finished, elapsed time is 3.638 seconds." int:severity="16"/>
  <message msg="Deferred data transformations have been finished, elapsed time is 0.226 seconds." int:severity="16"/>
  <message msg="Data model parameters have been set, elapsed time is 0.029 seconds." int:severity="16"/>
  <message msg="Precomputing frequently used data has been finished, elapsed time is 0.126 seconds." int:severity="16"/>
  <message msg="Redundant overtime data has been discarded, elapsed time is 0.005 seconds." int:severity="16"/>
  <message msg="Raw collector data has been discarded, elapsed time is 0.000 seconds." int:severity="16"/>
  <message msg="Finalizing the result took 9.882 seconds." int:severity="16"/>
 </message_entry_t>
 <message_entry_t int:status="0" cap="Failed to finalize the result" msg="" long:timeStamp="1634831176658">
  <message msg="Using result path `/gpfs/mira-home/cadams/Theta/larcv3_scaling/larcv_io_testing/r002hs'" int:severity="1"/>
  <message msg="The database has been cleared, elapsed time is 0.416 seconds." int:severity="16"/>
  <message msg="The current result was collected on another host. For proper symbol resolution, please specify search directories for the binaries of interest using the -search-dir command line option or &quot;Binary/Symbol Search&quot; dialog in GUI." int:severity="2"/>
  <message msg="Cannot load data file `/gpfs/mira-home/cadams/Theta/larcv3_scaling/larcv_io_testing/r002hs/data.0/emon.0.emon' (Failed to read CPU topology information!)." int:severity="4"/>
  <message msg="Raw data has been loaded to the database, elapsed time is 6.783 seconds." int:severity="16"/>
  <message msg="Data transformations have been finished, elapsed time is 0.017 seconds." int:severity="16"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_rt.so'." int:severity="2"/>
  <message msg="Cannot locate file `/usr/lib64/libnuma.so.1'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_intel_thread.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/pinruntime/libstlport-dynamic.so'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_intel_lp64.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/pinruntime/libc-dynamic.so'." int:severity="2"/>
  <message msg="Cannot locate file `/lus/theta-fs0/software/interpreters/python/3.6/intel/2019.3.075/bin/../lib/libpython3.6m.so.1.0'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libiomp5.so'." int:severity="2"/>
  <message msg="Cannot locate file `/usr/lib64/libmemkind.so'." int:severity="2"/>
  <message msg="Cannot locate file `/lus/theta-fs0/software/interpreters/python/3.6/intel/2019.3.075/bin/python3.6'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/cray/pe/atp/3.6.4/lib/libAtpSigHandler.so.1'." int:severity="2"/>
  <message msg="Cannot locate debugging information for file `/lib64/ld-linux-x86-64.so.2'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/gcc/9.3.0/snos/lib64/libstdc++.so.6'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_avx512_mic.so'." int:severity="2"/>
  <message msg="Cannot locate debugging information for file `/lib64/libm.so.6'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/_mklinit.cpython-36m-x86_64-linux-gnu.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/runtime/libittnotify_collector.so'." int:severity="2"/>
  <message msg="Cannot locate debugging information for file `/lib64/libpthread.so.0'." int:severity="2"/>
  <message msg="Cannot locate debugging information for file `/lib64/libdl.so.2'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/pinruntime/libpin3dwarf.so'." int:severity="2"/>
  <message msg="Cannot locate debugging information for file `/lib64/libz.so.1'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libintlc.so.5'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/lib64/libtpsstool.so'." int:severity="2"/>
  <message msg="Cannot locate file `/opt/intel/vtune_profiler_2020.0.0.605129/bin64/pinbin'." int:severity="2"/>
  <message msg="Cannot locate file `/soft/interpreters/python/3.6/intel/2019.3.075/lib/python3.6/site-packages/numpy/../../../libmkl_core.so'." int:severity="2"/>
  <message msg="Cannot locate debugging information for file `/lib64/libc.so.6'." int:severity="2"/>
  <message msg="Symbol resolution has been finished, elapsed time is 2.871 seconds." int:severity="16"/>
  <message msg="Deferred data transformations have been finished, elapsed time is 0.157 seconds." int:severity="16"/>
  <message msg="Data model parameters have been set, elapsed time is 0.032 seconds." int:severity="16"/>
  <message msg="Precomputing frequently used data has been finished, elapsed time is 0.095 seconds." int:severity="16"/>
  <message msg="Redundant overtime data has been discarded, elapsed time is 0.011 seconds." int:severity="16"/>
  <message msg="Raw collector data has been discarded, elapsed time is 0.000 seconds." int:severity="16"/>
  <message msg="Finalizing the result took 11.662 seconds." int:severity="16"/>
 </message_entry_t>
</bag>
